### PR TITLE
FIX: support sending the same notification to multiple device tokens.

### PR DESCRIPTION
**Pull request by kostadinstoilov**
According to the APNS* documentation you should send a frame for every device you would like to send a notification to. The current implementation only has one frame and in which it packs multiple device tokens. Without this patch only the last device on the token list gets a notification.

This patch is loosely based on https://github.com/MatejMainus/java-apns-gae/commit/9109fb8f1635f66de58135cb8f23be43e70db9a2, but it only contains a fix for multiple devices per notification. 

*https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW4

### CODE REVIEW

**Comment by berndfinal** [comment]
The current state of the library does not work on App Engine when sending one notification to multiple devices which will be fixed by this commit.

There was also another problem in this fork though https://github.com/MatejMainus/java-apns-gae which will also be fixed here. After sending data there won't be any response from apple servers but https://github.com/MatejMainus/java-apns-gae/commit/9109fb8f1635f66de58135cb8f23be43e70db9a2 expects one, thus code is stuck until the socket connection times out.

**Comment by ZsoltSafrany** [comment]
Good catch!

The documentation is not very explicit about whether you can send multiple "Device token" items (in the same frame) to send the same push notification to multiple recipient device tokens and optimize data transfer. I assumed I can but it seems I was wrong. 

It's interesting that even though I've implemented the (send push notification to multiple device tokens) feature I never used it and thus never noticed the issue myself. :)

Thank you for letting me know and for fixing it.

**Comment by ZsoltSafrany** [comment]
@kostadinstoilov, did you test your change whether it actually works? If not, I'm gonna revert this because #4 suggests it broke the code.

**Comment by kostadinstoilov** [comment]
Yes, I have tested it and I have been using it in production for several weeks now. I also ran the unit tests before I submitted the pull request. But I can setup a small test repo when I have some spare time to make sure it works.

**Comment by ZsoltSafrany** [comment]
Seems like #4 was a false alarm. Thank you @kostadinstoilov for the support!

**Pull request merged**
